export const RESTAURANT = {
  name: 'Ta Pinakia',
  nameGr: 'Τα Πινάκια',
  type: 'Mezedopoleio',
  tagline: 'Traditional Greek dining in the heart of Paphos',
  address: {
    street: 'Platia Kennedy Square 6',
    floor: '1st Floor',
    city: 'Paphos',
    postcode: '8047',
    country: 'Cyprus',
    googleMapsUrl: 'https://maps.google.com/?q=Ta+Pinakia+Paphos',
    embedUrl: 'https://www.google.com/maps?q=Ta+Pinakia+Taverna+Paphos+Cyprus&output=embed',
  },
  phone: '+35726818818',
  phoneDisplay: '+357 26 818818',
  whatsapp: 'https://wa.me/35726818818',
  instagram: 'https://www.instagram.com/tapinakia/',
  facebook: 'https://www.facebook.com/tapinakia/',
  hours: 'Mon–Sun 12:00–23:00',
  liveMusic: 'Wednesdays & Sundays',
  tripadvisor: {
    rating: 4.9,
    reviewCount: 142,
    rank: '#6 in Paphos',
    totalRestaurants: '570+',
    url: 'https://www.tripadvisor.com/Restaurant_Review-g190384-d25272691',
  },
}
